[package]
name = "bsq-rs"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = true
[dependencies]
memchr = "2.7.4"